# Generated by Django 3.1 on 2020-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200905_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('health', 'HEALTH'), ('music', 'MUSIC'), ('study', 'STUDY'), ('programming', 'PROGRAMMING'), ('gaming', 'GAMING'), ('food', 'FOOD'), ('movies', 'MOVIES'), ('cartoons', 'CARTOONS'), ('mining', 'MINING')], default='gaming', max_length=20),
        ),
    ]
